language: node_js
node_js:
  - "12.18.3"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
   - npm install -g firebase-tools
script:
  - npm install
  - ng build --prod
after_success:
  - firebase deploy --token $FIREBASE_TOKEN